-- Occupations are a built-in catalogue now: seed every entry and drop
-- leftovers that nobody is using. Only company_type stays editable.
insert into occupations (name, sort)
values
  ('Company Employee', 10),
  ('Government Officer', 20),
  ('State Enterprise Employee', 30),
  ('Business Owner / Merchant', 40),
  ('Self-Employed', 50),
  ('Freelancer', 60),
  ('Student', 70),
  ('Housewife / Househusband', 80),
  ('Retired', 90),
  ('Unemployed', 100),
  ('Farmer', 110),
  ('Livestock Farmer', 120),
  ('Fisherman', 130),
  ('Forestry Worker', 140),
  ('Agricultural Trader', 150),
  ('Restaurant Owner', 160),
  ('Chef / Cook', 170),
  ('Barista', 180),
  ('Street Food Vendor', 190),
  ('Bartender', 200),
  ('Food Delivery Rider', 210),
  ('Shop Owner', 220),
  ('Sales Assistant', 230),
  ('Market Trader', 240),
  ('Online Seller / E-commerce', 250),
  ('Wholesaler', 260),
  ('Cashier', 270),
  ('Taxi / Ride-hailing Driver', 280),
  ('Truck Driver', 290),
  ('Courier / Delivery Driver', 300),
  ('Logistics Staff', 310),
  ('Warehouse Worker', 320),
  ('Pilot / Cabin Crew', 330),
  ('Seafarer', 340),
  ('Construction Worker', 350),
  ('Contractor / Builder', 360),
  ('Electrician', 370),
  ('Plumber', 380),
  ('Carpenter', 390),
  ('Welder', 400),
  ('Painter / Decorator', 410),
  ('Architect', 420),
  ('Civil Engineer', 430),
  ('Surveyor', 440),
  ('Factory Worker', 450),
  ('Machine Operator', 460),
  ('Production Supervisor', 470),
  ('Quality Inspector', 480),
  ('Technician', 490),
  ('Software Developer', 500),
  ('IT Support', 510),
  ('Network / System Engineer', 520),
  ('Data Analyst', 530),
  ('UI / UX Designer', 540),
  ('Cybersecurity Specialist', 550),
  ('Game Developer', 560),
  ('Accountant', 570),
  ('Bookkeeper', 580),
  ('Auditor', 590),
  ('Bank Staff', 600),
  ('Financial Advisor', 610),
  ('Insurance Agent', 620),
  ('Trader / Investor', 630),
  ('Doctor', 640),
  ('Nurse', 650),
  ('Pharmacist', 660),
  ('Dentist', 670),
  ('Veterinarian', 680),
  ('Medical Technician', 690),
  ('Physiotherapist', 700),
  ('Caregiver', 710),
  ('Teacher', 720),
  ('University Lecturer', 730),
  ('Tutor', 740),
  ('Childcare Worker', 750),
  ('School Administrator', 760),
  ('Lawyer', 770),
  ('Notary', 780),
  ('Police Officer', 790),
  ('Military Personnel', 800),
  ('Firefighter', 810),
  ('Civil Servant', 820),
  ('Judge', 830),
  ('Journalist', 840),
  ('Photographer', 850),
  ('Videographer', 860),
  ('Graphic Designer', 870),
  ('Musician', 880),
  ('Content Creator / Influencer', 890),
  ('Actor / Performer', 900),
  ('Writer / Editor', 910),
  ('Hotel Staff', 920),
  ('Tour Guide', 930),
  ('Travel Agent', 940),
  ('Event Organiser', 950),
  ('Housekeeping Staff', 960),
  ('Hairdresser / Barber', 970),
  ('Beautician', 980),
  ('Massage Therapist', 990),
  ('Fitness Trainer', 1000),
  ('Nail Technician', 1010),
  ('Real Estate Agent', 1020),
  ('Property Manager', 1030),
  ('Landlord', 1040),
  ('Consultant', 1050),
  ('Marketing Specialist', 1060),
  ('HR Specialist', 1070),
  ('Administrative Staff', 1080),
  ('Customer Service', 1090),
  ('Translator / Interpreter', 1100),
  ('Procurement Officer', 1110),
  ('Security Guard', 1120),
  ('Cleaner', 1130),
  ('Maintenance Worker', 1140),
  ('Gardener', 1150),
  ('Researcher / Scientist', 1160),
  ('NGO / Charity Worker', 1170),
  ('Religious Worker', 1180),
  ('Other', 1190)
on conflict (name) do update set sort = excluded.sort;

delete from occupations o
where o.name not in ('Company Employee', 'Government Officer', 'State Enterprise Employee', 'Business Owner / Merchant', 'Self-Employed', 'Freelancer', 'Student', 'Housewife / Househusband', 'Retired', 'Unemployed', 'Farmer', 'Livestock Farmer', 'Fisherman', 'Forestry Worker', 'Agricultural Trader', 'Restaurant Owner', 'Chef / Cook', 'Barista', 'Street Food Vendor', 'Bartender', 'Food Delivery Rider', 'Shop Owner', 'Sales Assistant', 'Market Trader', 'Online Seller / E-commerce', 'Wholesaler', 'Cashier', 'Taxi / Ride-hailing Driver', 'Truck Driver', 'Courier / Delivery Driver', 'Logistics Staff', 'Warehouse Worker', 'Pilot / Cabin Crew', 'Seafarer', 'Construction Worker', 'Contractor / Builder', 'Electrician', 'Plumber', 'Carpenter', 'Welder', 'Painter / Decorator', 'Architect', 'Civil Engineer', 'Surveyor', 'Factory Worker', 'Machine Operator', 'Production Supervisor', 'Quality Inspector', 'Technician', 'Software Developer', 'IT Support', 'Network / System Engineer', 'Data Analyst', 'UI / UX Designer', 'Cybersecurity Specialist', 'Game Developer', 'Accountant', 'Bookkeeper', 'Auditor', 'Bank Staff', 'Financial Advisor', 'Insurance Agent', 'Trader / Investor', 'Doctor', 'Nurse', 'Pharmacist', 'Dentist', 'Veterinarian', 'Medical Technician', 'Physiotherapist', 'Caregiver', 'Teacher', 'University Lecturer', 'Tutor', 'Childcare Worker', 'School Administrator', 'Lawyer', 'Notary', 'Police Officer', 'Military Personnel', 'Firefighter', 'Civil Servant', 'Judge', 'Journalist', 'Photographer', 'Videographer', 'Graphic Designer', 'Musician', 'Content Creator / Influencer', 'Actor / Performer', 'Writer / Editor', 'Hotel Staff', 'Tour Guide', 'Travel Agent', 'Event Organiser', 'Housekeeping Staff', 'Hairdresser / Barber', 'Beautician', 'Massage Therapist', 'Fitness Trainer', 'Nail Technician', 'Real Estate Agent', 'Property Manager', 'Landlord', 'Consultant', 'Marketing Specialist', 'HR Specialist', 'Administrative Staff', 'Customer Service', 'Translator / Interpreter', 'Procurement Officer', 'Security Guard', 'Cleaner', 'Maintenance Worker', 'Gardener', 'Researcher / Scientist', 'NGO / Charity Worker', 'Religious Worker', 'Other')
  and not exists (select 1 from owners w where w.occupation_id = o.id);
